"""empty message

Revision ID: d3e8fc196b6e
Revises: 150996b7348e
Create Date: 2023-04-11 12:20:33.800017

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd3e8fc196b6e'
down_revision = '150996b7348e'
branch_labels = None
depends_on = None

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None, naming_convention=convention) as batch_op:
        batch_op.drop_constraint('fk_products_shop_id_shops', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_shop_id_shops'), 'shops', ['shop_id'], ['id'],
                                    onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('shops', schema=None, naming_convention=convention) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_shops_name'), ['name'])

    with op.batch_alter_table('tags', schema=None, naming_convention=convention) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tags_name'), ['name'])
        batch_op.drop_constraint('fk_tags_shop_id_shops', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_shop_id_shops'), 'shops', ['shop_id'], ['id'],
                                    onupdate='CASCADE')

    with op.batch_alter_table('tags_products', schema=None, naming_convention=convention) as batch_op:
        batch_op.drop_constraint('fk_tags_products_product_id_products', type_='foreignkey')
        batch_op.drop_constraint('fk_tags_products_tag_id_tags', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_products_product_id_products'), 'products', ['product_id'],
                                    ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tags_products_tag_id_tags'), 'tags', ['tag_id'], ['id'],
                                    onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_products_tag_id_tags'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tags_products_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_shop_id_shops'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_tags_name'), type_='unique')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shops_name'), type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_shop_id_shops'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    op.create_table('_alembic_tmp_products',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
                    sa.Column('price', sa.FLOAT(), nullable=False),
                    sa.Column('datetime_create', sa.DATETIME(), nullable=True),
                    sa.Column('datetime_update', sa.DATETIME(), nullable=True),
                    sa.Column('shop_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='fk_products_shop_id_shops',
                                            onupdate='CASCADE', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id', name='pk_products')
                    )
    # ### end Alembic commands ###
